# Generated by Django 5.1.4 on 2025-01-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_reports', 'Can view reports'), ('can_export_reports', 'Can export reports'), ('can_manage_users', 'Can manage users')], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_engineer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_technician',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'مدير'), ('engineer', 'مهندس'), ('technician', 'فني')], default='technician', max_length=20, verbose_name='الدور'),
        ),
    ]
