# Generated by Django 5.1.4 on 2025-01-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_engineer_email_engineer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='technician',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='الهاتف'),
        ),
    ]
